source 'http://rubygems.org' do
    gem 'rspec'
    gem 'cucumber', '2.3.2'
    gem 'pry'
    gem 'pry-nav'
    gem 'json'
    gem 'factory_girl'
    gem 'httparty'
    gem 'chronic'
    gem 'test-helpers', '0.3.0'
    gem 'faker'

    gem 'activerecord', '4.2.6'
    gem 'envme'
    gem 'couchbase', '1.3.15'
    gem 'mysql2'
end